baseURL = 'https://blog.luigiminardi.com/'
title = "Luigi Minardi"

defaultContentLanguage="en"

enableRobotsTXT=true
summaryLength=0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
