languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

copyright = "[&copy; 2026 Luigi Minardi](/license)"

[params]
    dateFormat="2 January 2006"
    mainSections=["posts", "projects"]

[params.author]
    name="Luigi Minardi"
    image = "img/me.jpeg"
    headline = "Backend Developer"
    bio = "I'm a backend developer, dancer and amateur car electromechanic. I like go, arch, neovim, techno, schranz, gabber, shuffle, JDMs and miatas. I'm also interested in drawing, fashion and other stuff."
    links = [
    #   { email = "mailto:hello@your_domain.com" },
    #   { link = "https://link-to-some-website.com/" },
        { github = "https://github.com/luigiminardi" },
        { codeberg = "https://codeberg.org/luigiminardi" },
        { kofi = "https://ko-fi.com/luigiminardi" },
        { linkedin = "https://linkedin.com/in/luigiminardi" },
        { stack-overflow = "https://stackoverflow.com/users/13636612/luigi-minardi" },
        { x-twitter = "https://twitter.com/luigiminardi_" },
    #   { youtube = "https://youtube.com/username" },
    ]
