languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1


[params]
    dateFormat="2 January 2006"

[params.author]
    name="Luigi Minardi"
    image = "img/me.jpeg"
    headline = "Backend Developer"
    bio = "I'm a programmer, I use mainly Go, Python, Typescript, Javascript, and some other langs. Tech Savvy, Arch and Neovim user, keyboard enthusiast, dancer, and some other things."
    links = [
    #   { email = "mailto:hello@your_domain.com" },
    #   { link = "https://link-to-some-website.com/" },
        { github = "https://github.com/luigiminardi" },
        { link = "https://codeberg.org/luigiminardi" },
        { kofi = "https://ko-fi.com/luigiminardi" },
        { linkedin = "https://linkedin.com/in/luigiminardi" },
        { stack-overflow = "https://stackoverflow.com/users/13636612/luigi-minardi" },
        { x-twitter = "https://twitter.com/luigiminardi_" },
    #   { youtube = "https://youtube.com/username" },
    ]
